'use client';
import { useState } from 'react';
import { useResource } from '@/hooks/use-resource';
import { useMutation } from '@/hooks/use-mutation';
import { requestData } from '@/lib/client-request';
import { LoadingState, ErrorState } from './RequestState';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Label } from './ui/label';
type Invitation = { id: string; email: string; expiresAt: string; usedAt: string | null; revokedAt: string | null };
type Staff = { technicians: { id: string; name: string; email: string; active: boolean; authVersion: number; invitationAccepted: boolean }[]; invitations: Invitation[] };
export function StaffManagement() {
    const resource = useResource<Staff>('/api/staff'); const { pending, run } = useMutation(); const [link, setLink] = useState(''), [message, setMessage] = useState('');
    async function invitation(path: string, data?: object) { const result = await requestData<{ url?: string }>(path, { method: 'POST', headers: { 'Content-Type': 'application/json' }, ...(data ? { body: JSON.stringify(data) } : {}) }); setLink(result.url || ''); setMessage(result.url ? 'Development link is available once below. No email was sent.' : 'Invitation created. Email delivery is not configured; no email was sent.'); await resource.reload(); }
    const status = (record: Invitation) => record.usedAt ? 'Accepted' : record.revokedAt ? 'Revoked' : new Date(record.expiresAt) <= new Date() ? 'Expired' : 'Pending';
    return <div className="max-w-4xl mx-auto space-y-6"><h1 className="text-2xl font-bold">Staff and technicians</h1><p className="text-slate-600">Manage technicians you onboard. All active technicians remain globally assignable. Manager accounts are provisioned by the operator.</p>
        <form className="rounded-lg border bg-white p-4 space-y-4" aria-busy={pending} onSubmit={event => { event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget)); void run(() => invitation('/api/staff', data), 'Could not create invitation'); }}><h2 className="text-lg font-semibold">Invite a technician</h2><div><Label htmlFor="staff-name">Technician name</Label><Input id="staff-name" name="name" required minLength={2} maxLength={100} /></div><div><Label htmlFor="staff-email">Technician email</Label><Input id="staff-email" name="email" type="email" required /></div><Button disabled={pending}>Create invitation</Button></form>
        {message && <p role="status">{message}</p>}{link && <div className="rounded-lg border bg-white p-4 space-y-3"><Label htmlFor="invitation-link">One-time development invitation URL</Label><Input id="invitation-link" value={link} readOnly className="min-w-0" /><Button variant="outline" onClick={() => void run(async () => { await navigator.clipboard.writeText(link); setMessage('Invitation link copied. Keep it private.'); }, 'Could not copy link')}>Copy invitation link</Button></div>}
        {resource.loading ? <LoadingState label="Loading account details…" /> : resource.error ? <ErrorState error={resource.error} retry={resource.reload} /> : resource.data && <><section className="space-y-3"><h2 className="text-lg font-semibold">Your technician accounts</h2>{resource.data.technicians.length === 0 && <p>No technicians onboarded yet.</p>}{resource.data.technicians.map(tech => <article key={tech.id} className="rounded-lg border bg-white p-4 flex flex-wrap gap-3 justify-between items-center"><div className="min-w-0 break-words [overflow-wrap:anywhere]"><h3 className="font-semibold">{tech.name}</h3><p>{tech.email}</p><p>{tech.active ? 'Active' : tech.invitationAccepted ? 'Inactive' : 'Awaiting invitation acceptance'}</p></div><Button disabled={pending || (!tech.active && !tech.invitationAccepted)} variant="outline" onClick={() => { if (!window.confirm((tech.active ? 'Deactivate' : 'Reactivate') + ' this technician? All their current sessions will be invalidated. Active work must be reassigned first.')) return; void run(async () => { await requestData('/api/staff/' + tech.id, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ active: !tech.active, expectedVersion: tech.authVersion }) }); await resource.reload(); }, 'Could not change account status'); }}>{tech.active ? 'Deactivate' : 'Reactivate'}</Button></article>)}</section>
        <section className="space-y-3"><h2 className="text-lg font-semibold">Recent invitations</h2>{resource.data.invitations.length === 0 && <p>No invitations yet.</p>}{resource.data.invitations.map(record => <article key={record.id} className="rounded-lg border bg-white p-4 space-y-3"><p className="break-words [overflow-wrap:anywhere]">{record.email} · {status(record)}</p><p className="text-sm text-slate-600">Expires {new Date(record.expiresAt).toLocaleString()}</p><div className="flex flex-wrap gap-2">{status(record) === 'Pending' && <Button disabled={pending} variant="outline" onClick={() => void run(async () => { await requestData('/api/staff/invitations/' + record.id, { method: 'DELETE' }); await resource.reload(); }, 'Could not revoke invitation')}>Revoke invitation</Button>}{!record.usedAt && <Button disabled={pending} variant="outline" onClick={() => void run(() => invitation('/api/staff/invitations/' + record.id), 'Could not renew invitation')}>Renew invitation</Button>}</div></article>)}</section></>}
    </div>;
}
